### ISSUE TITLE
Broken on latest julia v0.5 dev master

### ISSUE THREAD

**Issue by Ken-B** [MikeInnes/Requires.jl#19]
```jl
julia> using Requires
INFO: Precompiling module Requires...
# some warnings
ERROR: InitError: type Method has no field func
 [inlined code] from /Users/ken/.julia/v0.5/Requires/src/Requires.jl:3
 in (::Requires.##8#9)() at /Users/ken/.julia/v0.5/Requires/src/init.jl:17
 in __init__() at /Users/ken/.julia/v0.5/Requires/src/init.jl:24
 in _require_from_serialized(::Int64, ::Symbol, ::ASCIIString, ::Bool) at ./loading.jl:174
 in require(::Symbol) at ./loading.jl:365
 in eval(::Module, ::Any) at ./boot.jl:236
during initialization of module Requires
```

Julia 0.5 no longer has the `.func` field for functions, I believe. 
This package's metaprogramming is too advanced for me to provide a PR, sorry.

**Comment by MikeInnes** [comment]
I've actually simplified this package's metaprogramming a lot to work around this issue – although it's still hacking the compiler just a teensy bit. Should be fixed anyhow (for now).

**Comment by shashi** [comment]
Did you tag a release? Travis still has this problem....

**Comment by MikeInnes** [comment]
I don't know if tagging is the right thing until 0.5 is more stable, I've already had to fix this a couple of times. I suppose if you really want to I'm happy to give you the permissions. For release testing you can also checkout the package in the travis script, [e.g.](https://github.com/MikeInnes/Flow.jl/blob/master/.travis.yml).
