### ISSUE TITLE
Has there been a rebase of master?

### ISSUE THREAD

**Issue by davidanthoff** [MikeInnes/Requires.jl#20]
When I do a ``Pkg.checkout("Requires")`` I get a message ``WARNING: Cannot perform fast-forward merge.`` and the package is stuck at e2bae62fbed387. Somehow it looks to me as if master was rebased at some point?

**Comment by MikeInnes** [comment]
Hmm that's odd, it looks like we lost a merge commit there somehow.

Either way I guess you could just roll back a commit or two and then pull.

**Comment by davidanthoff** [comment]
Ok, that seemed to work.
