### ISSUE TITLE
Broken on 0.5

### ISSUE THREAD

**Issue by davidanthoff** [MikeInnes/Requires.jl#22]
I get this error right now, this is from the latest master and julia 0.5.0-dev+3993.
````
ERROR: LoadError: LoadError: UndefVarError: Requires not defined
 in require(::Symbol) at C:\Users\anthoff\.julia\v0.5\Requires\src\require.jl:10
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at .\loading.jl:174
 in _require_from_serialized(::Int64, ::Symbol, ::Bool) at .\loading.jl:202
 in require(::Symbol) at .\loading.jl:332
 in include_from_node1(::String) at .\loading.jl:426
 in eval(::Module, ::Any) at .\boot.jl:230
 [inlined code] from .\sysimg.jl:11
 in require(::Symbol) at .\loading.jl:357
 in include_from_node1(::String) at .\loading.jl:426
 in process_options(::Base.JLOptions) at .\client.jl:263
 in _start() at .\client.jl:319
while loading C:\Users\anthoff\.julia\v0.5\Judyp\src\Judyp.jl, in expression starting on line 8
while loading C:\Users\anthoff\source\4sD.jl\main.jl, in expression starting on line 1
````
I'm unable to create a short repo case, but maybe this is enough to diagnose? This bug is essentially keeping me from running anything on julia 0.5 right now... It is in particular preventing any further progress on julialang/julia#16047. Thanks for any help!

**Comment by MikeInnes** [comment]
This still an issue for you? I'm not seeing it on requires/julia master.

**Comment by davidanthoff** [comment]
Yes, still broken. I just gave you access to https://github.com/davidanthoff/Judyp.jl, if you clone that package and then try ``using Judyp`` you should be able to reproduce the error message.

**Comment by MikeInnes** [comment]
Great, thanks, I managed to reproduce this and push a fix.
