### ISSUE TITLE
Tag new release?

### ISSUE THREAD

**Issue by ranjanan** [MikeInnes/Requires.jl#27]
Hey, now that an RC0 candidate is up, you wanna tag a new release? The latest release breaks, but master works.

**Comment by davidavdav** [comment]
`ROCAnalysis` depends on `Requires`, so I'd like to see the latest version tagged as well, if that is possible.

**Comment by ranjanan** [comment]
I guess since @MikeInnes tagged a new version 2 days ago, this can be closed
