### ISSUE TITLE
0.5 deprecations

### ISSUE THREAD

**Issue by ViralBShah** [MikeInnes/Requires.jl#28]
Would be nice to fix these in preparation for 0.5

```
WARNING: Method definition require(Symbol) in module Base at loading.jl:345 overwritten in module Main at /Users/viral/.julia/v0.5/Requires/src/require.jl:12.
WARNING: Method definition require(Symbol) in module Base at loading.jl:345 overwritten in module Main at /Users/viral/.julia/v0.5/Requires/src/require.jl:12.
```

**Comment by MikeInnes** [comment]
These are not dep warnings as much as unavoidable method redefinition warnings. In Juno those are suppressed anyway so it's not an issue there. The only solution is to wait until 265 is fixed or to remove Requires.

**Comment by Nosferican** [comment]
I think this issue is academic and should be closed.
