### ISSUE TITLE
Thoughts on how we can make Requires precompile friendly. 

### ISSUE THREAD

**Issue by vchuravy** [MikeInnes/Requires.jl#33]
After working on #32 and #31 and gaining a better understanding of what Requires does. I had the following shower thoughts on what we need to do to remove some of the hackiness of Requires. 

As I understand it (and please correct me if I am wrong) the situation right now is that:
1. `@require [name] [block]` defines a dynamic block to be `eval`'ed *after* a package `[name]` has been loaded
2. In order to do that `Requires.jl` needs to listen to packages being loaded and therefore overwrites `Base.require`

This leads to a number of problems: overwriting a Base functions is bad and the dynamic nature is incompatible with precompiling

My proposal is to change `@require [name] [block]` turns into
```
@static if Pkg.installed($name) !== nothing
   using $name
   $block
else
    include_dependency("path/to/$name.jl") 
    # or
    # register_optional_dependency($name)
end
``` 

Which requires a change to Base that would allow us to register an optional dependency with mtime=0 
and if the package gets installed later this would lead to the package cache being invalidated.

Optional dependency version resolution would then be handled by Pkg3.

Thoughts, comments? 

cc: @tkelman @vtjnash

**Comment by vchuravy** [comment]
And of course `Pkg.installed` should be replaced by a `module_available` that is the equivalent to `require`.

**Comment by vchuravy** [comment]
I moved the discussion to https://discourse.julialang.org/t/optional-dependencies-requires-jl/3294 since it not only is about `Requires`.

**Comment by bjarthur** [comment]
in the meantime, it should at least be documented in the README that `Requires.jl` is not `__precompile__` friendly.
