### ISSUE TITLE
Still doesn't work on julia 0.6

### ISSUE THREAD

**Issue by davidanthoff** [MikeInnes/Requires.jl#34]
The repo is fairly simple: you need to be on ``master`` from [Query.jl](https://github.com/davidanthoff/Query.jl), and then a simple ``using Query`` hangs forever.

CC @vchuravy and @MikeInnes

**Comment by vchuravy** [comment]
How big is Query dependency graph? What happens if you set https://github.com/MikeInnes/Requires.jl/blob/master/src/oldcall.jl#L10 to a large number (e.g 64).
I am waiting for Julia 0.6 to branch so that I can propose a proper fix upstream and backport that to v0.6.1.
