### ISSUE TITLE
Type definition inside submodule that use require

### ISSUE THREAD

**Issue by mforets** [MikeInnes/Requires.jl#42]
Hi, 
consider that module `B` depends on `A`, and that some additional functionality is provided by a third package, let's say its `IntervalArithmetic` (but it doesn't really matter). If i define a new type in `A`, and want to use this type in `B`, things break as shown below in a minimal example.

In my (presumably wrong) mental model, `Requires.jl` just holds the code inside the `@require` block no matter if it is in `A.jl` and `B.jl`, until you run the `using IntervalArithmetic` block. Hence unless there is some race issue, definitions inside `A`  and `B` that mutually depend inside a `@require` should work.

In file `A.jl`:

```julia
__precompile__(true)
module A
    using Requires
    export B
    include("B.jl")
    @require IntervalArithmetic begin
        export myType
        struct myType{N<:Real}
            dat::N
        end
    end
end
```

In file `B.jl`:

```julia
__precompile__(true)
module B
    using A, Requires
    @require IntervalArithmetic begin
        export foo
        foo(x::A.myType) = x + 1.
    end
end
```

In a fresh session:

```julia
julia> include("A.jl"); using A

julia> using IntervalArithmetic
WARNING: Error requiring IntervalArithmetic from A.B:
UndefVarError: myType not defined
Stacktrace:
 [1] err(::A.B.##7#14, ::Module, ::String) at /Users/forets/.julia/v0.6/Requires/src/require.jl:42
 [2] withpath(::A.B.##6#13, ::String) at /Users/forets/.julia/v0.6/Requires/src/require.jl:32
 [3] (::A.B.##5#12)() at /Users/forets/.julia/v0.6/Requires/src/require.jl:53
 [4] _collect(::Array{Function,1}, ::Base.Generator{Array{Function,1},Requires.##3#4}, ::Base.EltypeUnknown, ::Base.HasShape) at ./array.jl:488
 [5] loadmod(::Symbol) at /Users/forets/.julia/v0.6/Requires/src/require.jl:20
 [6] require(::Symbol) at ./loading.jl:408
 [7] eval(::Module, ::Any) at ./boot.jl:235
 [8] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [9] macro expansion at ./REPL.jl:97 [inlined]
 [10] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
```

**Edit:** (maybe relevant)

```julia
julia> include("A.jl"); using A

julia> Requires.modlisteners
Dict{Symbol,Array{Function,1}} with 1 entry:
  :IntervalArithmetic => Function[A.B.#5, A.#5]
```

but one would like that `A.#5` comes *before* `A.B.#5` ?

**Comment by mforets** [comment]
Some debugging shows that it is indeed the order in which modules are entered in the `modlisteners` dictionary that causes this issue. Maybe `Requires` could provide a macro that allows reordering the dictionary such as `@modorder A B` in my example. Although for more nested examples it won't be that straightforward..

**Comment by MikeInnes** [comment]
You shouldn't try to define a type in a require block, let alone try to use it in another one. Requires is mainly intended for overloading method definitions, so it shouldn't produce any interface changes in the package.

Just lift the type def out of the block and it'll work.

**Comment by mforets** [comment]
Thanks for the insight. Yes, I'll keep your suggestion.

To be precise, here I intended to use `Requires` to provide "additional", or optional, features for our package. If I make an analogy with Plots: in the code base we have a `using RecipesBase` and a bunch of `@recipe` macros (these without startup time penalty); only if the user needs plotting in a session, `using Plots` enables that extra plotting functionality.

Again thanks for your time and for `Requires.jl`, that we find very useful.
