### ISSUE TITLE
relax UUID requirement

### ISSUE THREAD

**Issue by tpapp** [MikeInnes/Requires.jl#44]
Fixing some packages for `v0.7`, I am running into [this check](https://github.com/MikeInnes/Requires.jl/blob/b550be7e05c79aebf1ca21e739a8138162029eaf/src/require.jl#L63), eg

```julia
┌ Warning: Requires now needs a UUID: `@require Juno="uuid"`                                                                                                                                                         
└ @ PGFPlotsX tikzdocument.jl:297                                                                                                                                                                                    
┌ Warning: Requires now needs a UUID: `@require Colors="uuid"`                                                                                                                                                       
└ @ PGFPlotsX requires.jl:1                                                                                                                                                                                          
┌ Warning: Requires now needs a UUID: `@require DataFrames="uuid"`
└ @ PGFPlotsX requires.jl:29
┌ Warning: Requires now needs a UUID: `@require Contour="uuid"`
└ @ PGFPlotsX requires.jl:39
┌ Warning: Requires now needs a UUID: `@require StatsBase="uuid"`
└ @ PGFPlotsX requires.jl:60
```

I think this is a good feature in the long run, but I wonder if it could be relaxed while packages transition and get UUIDs.

**Comment by MikeInnes** [comment]
In general a package name without a UUID is ambiguous, so you can't really go without it. In the short term I'd be OK with just looking up the name in the default registry; that's probably quite easy if you can find the right function.

That said it's pretty easy to just look up the UUID of a package, [eg](https://github.com/JuliaRegistries/Uncurated/blob/976d38494f3f6941e25e439fbc9d62a3e53151ae/R/Requires/Package.toml#L2).

**Comment by tpapp** [comment]
Closing this issue in favor of #45.
