### ISSUE TITLE
UUID requirement in 0.7

### ISSUE THREAD

**Issue by denizyuret** [MikeInnes/Requires.jl#51]
If I understand correctly, @require will need to specify a particular version of a package using the UUID. Is there any way to specify "any version", or "a version newer than X" etc.?  For example, in AutoGrad, I want to load the derivatives for SpecialFunctions only if the package SpecialFunctions is available, and I don't care which exact version it is.

**Comment by tpapp** [comment]
I think you misunderstand, the UUID merely identifies the package, not the version.

**Comment by MikeInnes** [comment]
In particular you can find the Package.toml files with UUIDs here – https://github.com/JuliaRegistries/General/find/master

**Comment by denizyuret** [comment]
Thank you. I read the new Pkg documentation but this wasn’t clear. Is there
anything else I can read to understand the new system? (especially how to
transition an old package)

**Comment by timholy** [comment]
This is now documented in the README
