### ISSUE TITLE
Feature request: stub functions

### ISSUE THREAD

**Issue by BioTurboNick** [MikeInnes/Requires.jl#61]
I have a slightly different use that may or may not fall under this package, though I believe would fit well.

I am using Plots and have a `plot()` function for my data type. This is hidden within a @requires so that it is not loaded until the user requests it. I would like to have a stub function available so that if the user tries to use it without loading Plots, they can be told to do so.

The issue is that if I try to do this on my own, there ends up being a conflict when Plots is actually loaded, and the attempt to import the `plot()` function from Plots is ignored.

**Comment by MikeInnes** [comment]
Ideally the "stub function" should be one from Plots.jl. If the signature is `Foo.f(::Bar.G)` then you can't actually call the method without `Foo` and `Bar` being loaded, which is how Requires is designed to be used.

Failing that the best way is to define a function with a different type signature, e.g. `f(::Any)` with a more specific version in the require block.

I don't think there's anything Requires itself can do to make this easier though.

**Comment by BioTurboNick** [comment]
Ah, sure, f(::Any) might work. I was trying to be more specific. As long as the imported module overrides it, if it uses it's own f(::Any). I'll try that.
