### ISSUE TITLE
Defining a struct inside an @require block

### ISSUE THREAD

**Issue by DilumAluthge** [MikeInnes/Requires.jl#67]
@MikeInnes I saw [this thread](https://github.com/MikeInnes/Requires.jl/issues/42) from March 2018 in which you wrote that structs should not be defined inside an `@require` block.

Is that still the case? If so, how would you recommend that I accomplish something like the following? Essentially, I want to define a struct inside an `@require` block. I can't take the struct definition out of the `@requires` block because the struct subtypes an abstract type that is defined inside `MLJBase`, which is a package that I am lazy-loading with Requires.

```julia
module Example

using Requires

f(x::Integer) = "hello"

function __init__()
    @require MLJBase="a7f614a8-145f-11e9-1d2a-a57a1082229d" begin
        using .MLJBase
        mutable struct Foo <: MLJBase.Deterministic
            lambda::Float64
        end
        f(model::Foo) = "good-bye"
        MLJBase.fit(model::Foo, X, y) = "et cetera"
    end
end

end
```

**Comment by MikeInnes** [comment]
There's no good way to do this; you should be able to make your existing types cooperate with another package, like MLJ, just by defining new methods on them. If MLJ currently requires you to subtype something then ideally it should remove that restriction.

**Comment by DilumAluthge** [comment]
Unfortunately, I think MLJ dispatches differently based on the type, e.g. classification models vs regression models.

Looks like I might need to factor my MLJ-dependent code out into a different package.
